  version: "3.3"
    
  services:
    mariadb:
      build: requirements/mariadb/
      container_name: mariadb
      ports:
        - "127.0.0.1:3306:3306"
      networks:
        - backend
      env_file:
        - .env
      volumes:
        - db_data:/var/lib/mysql
      restart: on-failure

    nginx:
      build: requirements/nginx/
      container_name: nginx
      ports:
        - "443:443"
      networks:
        - backend
      env_file:
        - .env
      volumes:
        - wp_data:/var/www/html
      depends_on:
        - wordpress
      restart: on-failure
    
    wordpress:
      build: requirements/wordpress/
      container_name: wordpress
      ports:
        - "127.0.0.1:9000:9000"
      networks:
        - backend
      env_file:
        - .env
      volumes:
        - wp_data:/var/www/html
      depends_on:
        - mariadb
      restart: on-failure

  volumes:
    db_data:
      driver: local
      driver_opts:
        type: none
        device: /home/ababaei/data/db_data
        o: bind
    wp_data:
      driver: local
      driver_opts:
        type: none
        device: /home/ababaei/data/wp_data
        o: bind

  networks:
    backend:
