FROM debian:buster

RUN	apt-get update && apt-get -y install \
	php-fpm php php-cgi php-mysqli php-pear php-mbstring php-gettext libapache2-mod-php php-common php-phpseclib php-mysql \
	curl

#RUN mkdir /var/www/html
RUN chmod -R 755 /var/www/html

COPY www.conf /var/www/html

copy init.sh /usr/local/bin
ENTRYPOINT ["init.sh"]

EXPOSE 9000

CMD ["/usr/sbin/php-fpm7.3", "-F"]
